### ISSUE TITLE
missing view or tag at "table"

### ISSUE THREAD

**Issue by dan-klasson** [matthew342/volt-table#1]
I'm using volt-table 0.1.0. I had to put the following in my Gemfile to be able to install it:

```
 gem 'volt-table', github: 'matthew342/volt-table'
```

Although when I put `<:table source="{{ store.table }}" />` . I get the following error:

```
-- < missing view or tag at "table", make sure it's component is included in dependencies.rb > --
```

Did you perhaps change the use case on master?

**Comment by matthew342** [comment]
Hi @dan-klasson - sorry, somehow had missed this. No, haven't changed the use case. Make sure you include volt-table in your component by adding `component 'table'` to your `[component]/config/dependencies.rb`.
